/**
 * Common AC spare parts catalog — 50 items for local dev / seed import.
 * Images: Unsplash product-style photos per category.
 */
/** Local category tile images (served from frontend public/). */
const CATEGORY_IMAGE_URLS = {
  Compressors: "/images/categories/compressors.jpg",
  Capacitors: "/images/categories/capacitors.jpg",
  "Air Conditioner": "/images/categories/air-conditioner.jpg",
  Remotes: "/images/categories/remotes.jpg",
  Refrigerant: "/images/categories/refrigerant.jpg",
  Copper: "/images/categories/copper.jpg",
};

const IMG = {
  compressor: CATEGORY_IMAGE_URLS.Compressors,
  capacitor: CATEGORY_IMAGE_URLS.Capacitors,
  airConditioner: CATEGORY_IMAGE_URLS["Air Conditioner"],
  remote: CATEGORY_IMAGE_URLS.Remotes,
  refrigerant: CATEGORY_IMAGE_URLS.Refrigerant,
  copper: CATEGORY_IMAGE_URLS.Copper,
  fan: "/images/categories/copper.jpg",
  filter: "/images/categories/copper.jpg",
};

const COMMON_PRODUCTS = [
  // —— Compressors (8) ——
  {
    sku: "CMP-101",
    name: "Rotary Compressor 1.0T R32",
    category: "Compressors",
    brand: "Generic",
    price: 4200,
    stock: 12,
    description: "1 ton rotary compressor compatible with R32 split AC units.",
    compatibility: "1 ton split AC · R32",
    image_url: IMG.compressor,
  },
  {
    sku: "CMP-102",
    name: "Rotary Compressor 1.5T R32",
    category: "Compressors",
    brand: "Generic",
    price: 5800,
    stock: 10,
    description: "1.5 ton rotary compressor for residential split AC.",
    compatibility: "1.5 ton split AC · R32",
    image_url: IMG.compressor,
  },
  {
    sku: "CMP-103",
    name: "Rotary Compressor 2.0T R32",
    category: "Compressors",
    brand: "Generic",
    price: 7200,
    stock: 8,
    description: "2 ton rotary compressor for large room split AC.",
    compatibility: "2 ton split AC · R32",
    image_url: IMG.compressor,
  },
  {
    sku: "CMP-104",
    name: "Rotary Compressor 1.5T R410A",
    category: "Compressors",
    brand: "Generic",
    price: 5500,
    stock: 6,
    description: "1.5 ton R410A rotary compressor replacement unit.",
    compatibility: "1.5 ton split AC · R410A",
    image_url: IMG.compressor,
  },
  {
    sku: "CMP-105",
    name: "Scroll Compressor 2.0T R32",
    category: "Compressors",
    brand: "Daikin",
    price: 11500,
    stock: 4,
    description: "Premium scroll compressor for inverter split AC.",
    compatibility: "2 ton inverter split · R32",
    image_url: IMG.compressor,
  },
  {
    sku: "CMP-106",
    name: "Window AC Compressor 1.5T",
    category: "Compressors",
    brand: "Generic",
    price: 3800,
    stock: 7,
    description: "Replacement compressor for 1.5 ton window AC.",
    compatibility: "Window AC 1.5 ton",
    image_url: IMG.compressor,
  },
  {
    sku: "CMP-107",
    name: "Compressor Mounting Kit",
    category: "Compressors",
    brand: "Smart Cool Care",
    price: 280,
    stock: 40,
    description: "Rubber mounts, bolts and washers for compressor installation.",
    compatibility: "Universal split AC",
    image_url: IMG.compressor,
  },
  {
    sku: "CMP-108",
    name: "Compressor Terminal Cover",
    category: "Compressors",
    brand: "Generic",
    price: 120,
    stock: 55,
    description: "Plastic terminal box cover for outdoor compressor unit.",
    compatibility: "Universal",
    image_url: IMG.compressor,
  },

  // —— Capacitors (8) ——
  {
    sku: "CAP-201",
    name: "Run Capacitor 25µF 450V",
    category: "Capacitors",
    brand: "Generic",
    price: 145,
    stock: 80,
    description: "Standard run capacitor for single-phase AC motors.",
    compatibility: "1 ton split AC",
    image_url: IMG.capacitor,
  },
  {
    sku: "CAP-202",
    name: "Run Capacitor 35µF 450V",
    category: "Capacitors",
    brand: "Generic",
    price: 165,
    stock: 75,
    description: "35 microfarad run capacitor — most common size.",
    compatibility: "1–1.5 ton split AC",
    image_url: IMG.capacitor,
  },
  {
    sku: "CAP-203",
    name: "Run Capacitor 45µF 450V",
    category: "Capacitors",
    brand: "Generic",
    price: 185,
    stock: 60,
    description: "45µF capacitor for larger outdoor fan motors.",
    compatibility: "1.5–2 ton split AC",
    image_url: IMG.capacitor,
  },
  {
    sku: "CAP-204",
    name: "Start Capacitor 80µF 250V",
    category: "Capacitors",
    brand: "Generic",
    price: 220,
    stock: 35,
    description: "Start capacitor for compressor startup assist.",
    compatibility: "Window & split AC",
    image_url: IMG.capacitor,
  },
  {
    sku: "CAP-205",
    name: "Dual Run Capacitor 35+5µF",
    category: "Capacitors",
    brand: "Generic",
    price: 295,
    stock: 45,
    description: "Combined fan + compressor capacitor in one unit.",
    compatibility: "Split AC outdoor unit",
    image_url: IMG.capacitor,
  },
  {
    sku: "CAP-206",
    name: "Capacitor Mounting Clip Set",
    category: "Capacitors",
    brand: "Smart Cool Care",
    price: 45,
    stock: 100,
    description: "Metal clips for securing capacitors in outdoor panel.",
    compatibility: "Universal",
    image_url: IMG.capacitor,
  },
  {
    sku: "CAP-207",
    name: "Run Capacitor 50µF 440V",
    category: "Capacitors",
    brand: "Epcos",
    price: 210,
    stock: 40,
    description: "Heavy-duty run capacitor for commercial AC.",
    compatibility: "2+ ton units",
    image_url: IMG.capacitor,
  },
  {
    sku: "CAP-208",
    name: "Capacitor Discharge Resistor",
    category: "Capacitors",
    brand: "Generic",
    price: 35,
    stock: 90,
    description: "Bleeder resistor for safe capacitor discharge.",
    compatibility: "Universal",
    image_url: IMG.capacitor,
  },

  // —— PCB Boards (8) ——
  {
    sku: "PCB-301",
    name: "Universal Indoor PCB 1.0–1.5T",
    category: "Air Conditioner",
    brand: "Generic",
    price: 1850,
    stock: 15,
    description: "Replacement indoor control board for split AC.",
    compatibility: "1–1.5 ton · multi-brand",
    image_url: IMG.airConditioner,
  },
  {
    sku: "PCB-302",
    name: "Voltas Indoor PCB Kit",
    category: "Air Conditioner",
    brand: "Voltas",
    price: 2400,
    stock: 8,
    description: "OEM-style indoor PCB for Voltas split models.",
    compatibility: "Voltas split AC",
    image_url: IMG.airConditioner,
  },
  {
    sku: "PCB-303",
    name: "Daikin Outdoor Inverter PCB",
    category: "Air Conditioner",
    brand: "Daikin",
    price: 5200,
    stock: 5,
    description: "Outdoor inverter driver board for Daikin split.",
    compatibility: "Daikin inverter models",
    image_url: IMG.airConditioner,
  },
  {
    sku: "PCB-304",
    name: "LG Indoor Display PCB",
    category: "Air Conditioner",
    brand: "LG",
    price: 2100,
    stock: 7,
    description: "Indoor unit main PCB with display interface.",
    compatibility: "LG split AC",
    image_url: IMG.airConditioner,
  },
  {
    sku: "PCB-305",
    name: "Samsung Outdoor PCB Module",
    category: "Air Conditioner",
    brand: "Samsung",
    price: 3800,
    stock: 6,
    description: "Outdoor unit control module for Samsung AC.",
    compatibility: "Samsung split AC",
    image_url: IMG.airConditioner,
  },
  {
    sku: "PCB-306",
    name: "Hitachi Sensor PCB",
    category: "Air Conditioner",
    brand: "Hitachi",
    price: 1650,
    stock: 9,
    description: "Room temperature sensor interface board.",
    compatibility: "Hitachi split AC",
    image_url: IMG.airConditioner,
  },
  {
    sku: "PCB-307",
    name: "Universal Outdoor PCB 2T",
    category: "Air Conditioner",
    brand: "Generic",
    price: 2900,
    stock: 10,
    description: "Outdoor unit control PCB for 2 ton splits.",
    compatibility: "2 ton split AC",
    image_url: IMG.airConditioner,
  },
  {
    sku: "PCB-308",
    name: "PCB Wiring Harness Kit",
    category: "Air Conditioner",
    brand: "Smart Cool Care",
    price: 350,
    stock: 25,
    description: "Connector harness for PCB replacement jobs.",
    compatibility: "Universal split AC",
    image_url: IMG.airConditioner,
  },

  // —— Remotes (8) ——
  {
    sku: "RMT-401",
    name: "Universal AC Remote CH-18",
    category: "Remotes",
    brand: "Generic",
    price: 280,
    stock: 60,
    description: "1000-in-1 universal remote for split & window AC.",
    compatibility: "Multi-brand",
    image_url: IMG.remote,
  },
  {
    sku: "RMT-402",
    name: "Voltas AC Remote",
    category: "Remotes",
    brand: "Voltas",
    price: 450,
    stock: 22,
    description: "Compatible remote for Voltas split AC models.",
    compatibility: "Voltas",
    image_url: IMG.remote,
  },
  {
    sku: "RMT-403",
    name: "Daikin AC Remote",
    category: "Remotes",
    brand: "Daikin",
    price: 680,
    stock: 18,
    description: "OEM-style remote for Daikin inverter AC.",
    compatibility: "Daikin",
    image_url: IMG.remote,
  },
  {
    sku: "RMT-404",
    name: "LG AC Remote",
    category: "Remotes",
    brand: "LG",
    price: 520,
    stock: 20,
    description: "Replacement remote for LG dual inverter AC.",
    compatibility: "LG",
    image_url: IMG.remote,
  },
  {
    sku: "RMT-405",
    name: "Samsung Wind-Free Remote",
    category: "Remotes",
    brand: "Samsung",
    price: 590,
    stock: 15,
    description: "Remote with display for Samsung wind-free series.",
    compatibility: "Samsung",
    image_url: IMG.remote,
  },
  {
    sku: "RMT-406",
    name: "Blue Star AC Remote",
    category: "Remotes",
    brand: "Blue Star",
    price: 480,
    stock: 14,
    description: "Compatible remote for Blue Star split models.",
    compatibility: "Blue Star",
    image_url: IMG.remote,
  },
  {
    sku: "RMT-407",
    name: "Remote Battery Pack (2×AAA)",
    category: "Remotes",
    brand: "Smart Cool Care",
    price: 40,
    stock: 120,
    description: "Alkaline batteries for AC remotes.",
    compatibility: "Universal",
    image_url: IMG.remote,
  },
  {
    sku: "RMT-408",
    name: "Remote Wall Holder",
    category: "Remotes",
    brand: "Generic",
    price: 85,
    stock: 70,
    description: "Adhesive wall mount bracket for AC remote.",
    compatibility: "Universal",
    image_url: IMG.remote,
  },

  // —— Refrigerant (7) ——
  {
    sku: "REF-501",
    name: "R32 Refrigerant Gas 1 kg",
    category: "Refrigerant",
    brand: "Honeywell",
    price: 950,
    stock: 30,
    description: "1 kg R32 refill canister for split AC.",
    compatibility: "R32 systems",
    image_url: IMG.refrigerant,
  },
  {
    sku: "REF-502",
    name: "R410A Refrigerant Gas 1 kg",
    category: "Refrigerant",
    brand: "Honeywell",
    price: 880,
    stock: 25,
    description: "1 kg R410A canister for older split models.",
    compatibility: "R410A systems",
    image_url: IMG.refrigerant,
  },
  {
    sku: "REF-503",
    name: "R22 Refrigerant Gas 1 kg",
    category: "Refrigerant",
    brand: "Generic",
    price: 720,
    stock: 15,
    description: "R22 gas for legacy window and split AC.",
    compatibility: "R22 systems only",
    image_url: IMG.refrigerant,
  },
  {
    sku: "REF-504",
    name: "Refrigerant Charging Hose Set",
    category: "Refrigerant",
    brand: "Smart Cool Care",
    price: 650,
    stock: 18,
    description: "Colour-coded hoses with gauges for gas charging.",
    compatibility: "Universal",
    image_url: IMG.refrigerant,
  },
  {
    sku: "REF-505",
    name: "Vacuum Pump Adapter Kit",
    category: "Refrigerant",
    brand: "Generic",
    price: 420,
    stock: 12,
    description: "Adapters for vacuum pump and manifold gauge.",
    compatibility: "Universal",
    image_url: IMG.refrigerant,
  },
  {
    sku: "REF-506",
    name: "Leak Detector Spray 400ml",
    category: "Refrigerant",
    brand: "Generic",
    price: 195,
    stock: 45,
    description: "Bubble-forming leak detection spray for joints.",
    compatibility: "Universal",
    image_url: IMG.refrigerant,
  },
  {
    sku: "REF-507",
    name: "Flaring Tool Set",
    category: "Refrigerant",
    brand: "Smart Cool Care",
    price: 780,
    stock: 10,
    description: "Tube cutter and flaring tool for copper lines.",
    compatibility: "Installation use",
    image_url: IMG.refrigerant,
  },

  // —— Installation (11) ——
  {
    sku: "INS-601",
    name: "Copper Pipe 1/4 inch (15m roll)",
    category: "Copper",
    brand: "Smart Cool Care",
    price: 480,
    stock: 35,
    description: "Insulated copper line for AC gas piping.",
    compatibility: "Split AC installation",
    image_url: IMG.copper,
  },
  {
    sku: "INS-602",
    name: "Copper Pipe 3/8 inch (15m roll)",
    category: "Copper",
    brand: "Smart Cool Care",
    price: 720,
    stock: 28,
    description: "Heavy-duty copper pipe for 1.5–2 ton AC.",
    compatibility: "1.5–2 ton split AC",
    image_url: IMG.copper,
  },
  {
    sku: "INS-603",
    name: "Outdoor Wall Bracket Pair",
    category: "Copper",
    brand: "Generic",
    price: 380,
    stock: 40,
    description: "Galvanized steel bracket for outdoor unit mount.",
    compatibility: "Universal split AC",
    image_url: IMG.copper,
  },
  {
    sku: "INS-604",
    name: "Indoor Mounting Plate",
    category: "Copper",
    brand: "Generic",
    price: 220,
    stock: 50,
    description: "Wall plate for indoor evaporator unit.",
    compatibility: "Universal split AC",
    image_url: IMG.copper,
  },
  {
    sku: "INS-605",
    name: "Drain Pipe 16mm (10m)",
    category: "Copper",
    brand: "Generic",
    price: 145,
    stock: 65,
    description: "Flexible PVC drain hose for condensate water.",
    compatibility: "Universal",
    image_url: IMG.copper,
  },
  {
    sku: "INS-606",
    name: "Installation Kit Basic",
    category: "Copper",
    brand: "Smart Cool Care",
    price: 1250,
    stock: 20,
    description: "Copper pipes, drain, tape, brackets — 1 ton kit.",
    compatibility: "1 ton split AC install",
    image_url: IMG.copper,
  },
  {
    sku: "INS-607",
    name: "Installation Kit Premium 1.5T",
    category: "Copper",
    brand: "Smart Cool Care",
    price: 1680,
    stock: 15,
    description: "Full install kit for 1.5 ton split including insulation.",
    compatibility: "1.5 ton split AC install",
    image_url: IMG.copper,
  },
  {
    sku: "INS-608",
    name: "Cable 4 Core 1.5mm (20m)",
    category: "Copper",
    brand: "Generic",
    price: 890,
    stock: 22,
    description: "Power interconnect cable indoor to outdoor.",
    compatibility: "Split AC wiring",
    image_url: IMG.copper,
  },
  {
    sku: "INS-609",
    name: "Outdoor Fan Motor 1.5T",
    category: "Copper",
    brand: "Generic",
    price: 1350,
    stock: 11,
    description: "Replacement condenser fan motor for outdoor unit.",
    compatibility: "1.5 ton outdoor unit",
    image_url: IMG.fan,
  },
  {
    sku: "INS-610",
    name: "Indoor Blower Motor",
    category: "Copper",
    brand: "Generic",
    price: 1180,
    stock: 9,
    description: "Evaporator blower motor for indoor unit.",
    compatibility: "1–1.5 ton indoor unit",
    image_url: IMG.fan,
  },
  {
    sku: "INS-611",
    name: "AC Filter Set (2 pcs)",
    category: "Copper",
    brand: "Generic",
    price: 320,
    stock: 55,
    description: "Washable anti-dust filters for split AC indoor.",
    compatibility: "Universal split AC",
    image_url: IMG.filter,
  },
];

module.exports = { COMMON_PRODUCTS, CATEGORY_IMAGE_URLS };
